#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: R
# autospec version: v21
# autospec commit: f4a13a5
#
Name     : R-reshape2
Version  : 1.4.4
Release  : 97
URL      : https://cran.r-project.org/src/contrib/reshape2_1.4.4.tar.gz
Source0  : https://cran.r-project.org/src/contrib/reshape2_1.4.4.tar.gz
Summary  : Flexibly Reshape Data: A Reboot of the Reshape Package
Group    : Development/Tools
License  : MIT
Requires: R-reshape2-lib = %{version}-%{release}
Requires: R-Rcpp
Requires: R-plyr
Requires: R-stringr
BuildRequires : R-Rcpp
BuildRequires : R-plyr
BuildRequires : R-stringr
BuildRequires : buildreq-R
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
# reshape2
<!-- badges: start -->
[![R build status](https://github.com/hadley/reshape/workflows/R-CMD-check/badge.svg)](https://github.com/hadley/reshape/actions)
[![Codecov test coverage](https://codecov.io/gh/hadley/reshape/branch/master/graph/badge.svg)](https://codecov.io/gh/hadley/reshape?branch=master)
<!-- badges: end -->

%package lib
Summary: lib components for the R-reshape2 package.
Group: Libraries

%description lib
lib components for the R-reshape2 package.


%prep
%setup -q -n reshape2
pushd ..
cp -a reshape2 buildavx2
popd
pushd ..
cp -a reshape2 buildavx512
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1737155981

%install
export SOURCE_DATE_EPOCH=1737155981
rm -rf %{buildroot}
LANG=C.UTF-8
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -flto -fno-semantic-interposition "
FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -flto -fno-semantic-interposition "
AR=gcc-ar
RANLIB=gcc-ranlib
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library
mkdir -p %{buildroot}-v3/usr/lib64/R/library
mkdir -p %{buildroot}-v4/usr/lib64/R/library
mkdir -p %{buildroot}-va/usr/lib64/R/library

mkdir -p ~/.R
echo "CFLAGS = $CFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper" > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL  --install-tests --use-LTO --built-timestamp=${SOURCE_DATE_EPOCH} --data-compress=none --compress=none --build  -l %{buildroot}-v3/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL --preclean  --install-tests --use-LTO --no-test-load --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}-v4/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean  --use-LTO --install-tests --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library .
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc . || :

/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}
/usr/bin/elf-move.py avx512 %{buildroot}-v4 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)
/usr/lib64/R/library/reshape2/CITATION
/usr/lib64/R/library/reshape2/DESCRIPTION
/usr/lib64/R/library/reshape2/INDEX
/usr/lib64/R/library/reshape2/LICENSE
/usr/lib64/R/library/reshape2/Meta/Rd.rds
/usr/lib64/R/library/reshape2/Meta/data.rds
/usr/lib64/R/library/reshape2/Meta/features.rds
/usr/lib64/R/library/reshape2/Meta/hsearch.rds
/usr/lib64/R/library/reshape2/Meta/links.rds
/usr/lib64/R/library/reshape2/Meta/nsInfo.rds
/usr/lib64/R/library/reshape2/Meta/package.rds
/usr/lib64/R/library/reshape2/NAMESPACE
/usr/lib64/R/library/reshape2/NEWS.md
/usr/lib64/R/library/reshape2/R/reshape2
/usr/lib64/R/library/reshape2/R/reshape2.rdb
/usr/lib64/R/library/reshape2/R/reshape2.rdx
/usr/lib64/R/library/reshape2/data/Rdata.rdb
/usr/lib64/R/library/reshape2/data/Rdata.rds
/usr/lib64/R/library/reshape2/data/Rdata.rdx
/usr/lib64/R/library/reshape2/help/AnIndex
/usr/lib64/R/library/reshape2/help/aliases.rds
/usr/lib64/R/library/reshape2/help/paths.rds
/usr/lib64/R/library/reshape2/help/reshape2.rdb
/usr/lib64/R/library/reshape2/help/reshape2.rdx
/usr/lib64/R/library/reshape2/html/00Index.html
/usr/lib64/R/library/reshape2/html/R.css
/usr/lib64/R/library/reshape2/tests/testthat.R
/usr/lib64/R/library/reshape2/tests/testthat/test-cast.r
/usr/lib64/R/library/reshape2/tests/testthat/test-margins.r
/usr/lib64/R/library/reshape2/tests/testthat/test-melt.r

%files lib
%defattr(-,root,root,-)
/V3/usr/lib64/R/library/reshape2/libs/reshape2.so
/V4/usr/lib64/R/library/reshape2/libs/reshape2.so
/usr/lib64/R/library/reshape2/libs/reshape2.so
